# Generated by Django 5.0.1 on 2024-02-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precipitation_index', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weather_condition', models.CharField(max_length=255)),
            ],
        ),
    ]
